#!/usr/bin/env bash
# a script that displays numbers from 1 to 100

n=1

while [ "$n" -le 100 ]; do
	if ! (( n % 3 )) && ! (( n % 5 )); then
		echo "Fizzbuzz"
	elif ! (( n % 3 )); then
		echo "Fizz"
	elif ! (( n % 5 )); then
		echo "Buzz"
	else
		echo "$n"
fi
	((n++))
done
