#!/usr/bin/env bash
# A script that creates the file /var/run/myscript.pid containind itsPID

file="/var/run/myscript.pid
if [ ! -e "$file" ]; then
	touch "$file"
fi
sleep 2 &
echo "$!" > "$file"
trap 'echo "I hate the kill command"; rm "$file"; exist' SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGQUIT
while true;do
	echo "To infinity and beyond"
	sleep 2
done
